### ISSUE TITLE
Incorrect Docstring/ behaviour for use_ssh_tunnel

### ISSUE THREAD

**Issue by helegraf** [tornede/py_experimenter#187]
- PyExperimenter version: 1.4.1
- Database provider: mysql
- Python version: 3.11.4
- Operating System: MacOS Sonoma 14.2.1

### Description

In the main PyExperimenter class, `use_ssh_tunnel` is described as follows 
```
If the used dataabse is sqlite this parameter is ignored Otherwise: If the database is mysql,
            and `use_ssh_tunnel == True` the ssh credentials provided in `database_credential_file_path` used to establish
            a ssh tunnel to the database. If `use_ssh_tunnel == True` but no ssh credentials are provided in
            `database_credential_file_path`, no ssh tunnel is established. Defaults to True.
```

However, if one sets `use_ss_tunnel` to `True` and uses `provider: mysql` in the config file, then an `Ssh` section specifying the tunnel is expected (see error below).

(minor: typo/ formatting issue of docstring)

#### Raised Following Rrror

```text
[2024-04-03 12:12:30,599][root][ERROR] - Missing key Ssh
    full_key: CREDENTIALS.Connection.Ssh
    object_type=dict
[2024-04-03 12:12:30,599][root][ERROR] - Invalid credentials file!
Error executing job with overrides: ['+optimizer/DUMMY=config', '+problem/DUMMY=config', 'seed=1']
Traceback (most recent call last):
  File "/opt/anaconda3/envs/smacbenchmarking/lib/python3.11/site-packages/py_experimenter/database_connector_mysql.py", line 107, in _get_database_credentials
    server_address = credential_config["CREDENTIALS"]["Connection"]["Ssh"]["server"]
                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^
  File "/opt/anaconda3/envs/smacbenchmarking/lib/python3.11/site-packages/omegaconf/dictconfig.py", line 375, in __getitem__
    self._format_and_raise(key=key, value=None, cause=e)
  File "/opt/anaconda3/envs/smacbenchmarking/lib/python3.11/site-packages/omegaconf/base.py", line 231, in _format_and_raise
    format_and_raise(
  File "/opt/anaconda3/envs/smacbenchmarking/lib/python3.11/site-packages/omegaconf/_utils.py", line 899, in format_and_raise
    _raise(ex, cause)
  File "/opt/anaconda3/envs/smacbenchmarking/lib/python3.11/site-packages/omegaconf/_utils.py", line 797, in _raise
    raise ex.with_traceback(sys.exc_info()[2])  # set env var OC_CAUSE=1 for full trace
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/smacbenchmarking/lib/python3.11/site-packages/omegaconf/dictconfig.py", line 369, in __getitem__
    return self._get_impl(key=key, default_value=_DEFAULT_MARKER_)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/smacbenchmarking/lib/python3.11/site-packages/omegaconf/dictconfig.py", line 442, in _get_impl
    node = self._get_child(
           ^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/smacbenchmarking/lib/python3.11/site-packages/omegaconf/basecontainer.py", line 73, in _get_child
    child = self._get_node(
            ^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/smacbenchmarking/lib/python3.11/site-packages/omegaconf/dictconfig.py", line 480, in _get_node
    raise ConfigKeyError(f"Missing key {key!s}")
omegaconf.errors.ConfigKeyError: Missing key Ssh
    full_key: CREDENTIALS.Connection.Ssh
    object_type=dict

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/anaconda3/envs/smacbenchmarking/lib/python3.11/site-packages/py_experimenter/database_connector_mysql.py", line 68, in _test_connection
    connection = self.connect()
                 ^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/smacbenchmarking/lib/python3.11/site-packages/py_experimenter/database_connector_mysql.py", line 90, in connect
    credentials = dict(self._get_database_credentials())
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/smacbenchmarking/lib/python3.11/site-packages/py_experimenter/database_connector_mysql.py", line 122, in _get_database_credentials
    raise DatabaseCreationError("Invalid credentials file!")
py_experimenter.exceptions.DatabaseCreationError: Invalid credentials file!

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/helenagraf/Documents/git/SMACBenchmarking/smacbenchmarking/container/create_cluster_configs.py", line 33, in main
    experimenter = PyExperimenter(experiment_configuration_file_path=experiment_configuration_file_path,
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/smacbenchmarking/lib/python3.11/site-packages/py_experimenter/experimenter.py", line 120, in __init__
    self.db_connector = DatabaseConnectorMYSQL(
                        ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/smacbenchmarking/lib/python3.11/site-packages/py_experimenter/database_connector_mysql.py", line 26, in __init__
    super().__init__(database_configuration, use_codecarbon, logger)
  File "/opt/anaconda3/envs/smacbenchmarking/lib/python3.11/site-packages/py_experimenter/database_connector.py", line 28, in __init__
    self._test_connection()
  File "/opt/anaconda3/envs/smacbenchmarking/lib/python3.11/site-packages/py_experimenter/database_connector_mysql.py", line 71, in _test_connection
    raise DatabaseConnectionError(err)
py_experimenter.exceptions.DatabaseConnectionError: Invalid credentials file!
```

**Comment by tornede** [comment]
Solution: 

- [ ] the PyExperimenter parameter `use_ssh_tunnel` will be moved to the config file (so there is none in the PyExperimenter class left)
- [ ] If `use_ssh_tunnel` is True in the config file and no further details are given, this will result in an error (as seen above)

**Comment by LukasFehring** [comment]
> * [ ]  the PyExperimenter parameter `use_ssh_tunnel` will be moved to the config file (so there is none in the PyExperimenter class left)
I disagree with this idea for various reasons:
1. Depending on the place of work you will need to change the parameter.. For example: If you have the same codebase locally, and on the cluster, you will want to change this parameter. Using python to check if ssh is needed is quite easy, and a single point of failure. Moving it into the config results in a big hustle
2. If running multiple experimenters on the same machine in parallel, you do not want to establish mutlple ssh connections. However, configuring the parameter over a config file, will make it harder to configure the object instances appropriately.

>  If use_ssh_tunnel is True in the config file and no further details are given, this will result in an error (as seen above)
I agree with this, but will make the error more expessive

**Comment by tornede** [comment]
Regarding the `use_ssh_tunnel` flag: after discussion we will provide both, config file and code. If given in code, this overwrites whatever has been given via config file
